---
resource_types:
  - name: maven-resource
    type: docker-image
    source:
      repository: nulldriver/maven-resource
      tag: latest

resources:
  - name: source-code-from-github
    type: git
    source:
      uri: https://github.com/pavloshumylo/payment-splitter.git
      branch: master
      username: ((github_username))
      password: ((github_password))
  - name: pcf-access
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: ((pcf_username))
      password: ((pcf_password))
      organization: pavlo.shumylo-org
      space: development
      skip_cert_check: true
  - name: artifact
    type: maven-resource
    source:
      url: http://172.25.11.156:8098/repository/maven-releases/
      snapshot_url: http://172.25.11.156:8098/repository/maven-snapshots/
      artifact: com.eleks:UserSvc:jar
      username: ((nexus_username))
      password: ((nexus_password))
      skip_cert_check: true      

jobs:
  - name: user-svc-build-job
    plan:
      - get: source-code-from-github
        trigger: true
      - task: build-task
        file: source-code-from-github/ci/usersvc/task/build-task.yml
      - put: artifact
        params:
          file: user-svc-build/UserService-*.jar
          pom_file: user-svc-build/pom.xml
  - name: user-svc-deploy-job
    plan:
      - get: source-code-from-github
        passed: [user-svc-build-job]
      - get: artifact
        passed: [user-svc-build-job]
        trigger: true
      - put: pcf-access
        params:
          manifest: source-code-from-github/ci/usersvc/manifest.yml
          path: artifact/UserSvc-*.jar